name: mini-ola Release
on:
  push:
    branches: ["pre-alpha"]
    tags:
      - 'pre-alpha'
  pull_request:
    branches: ["pre-alpha"]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:

  linux-x86-64:
    name: Linux x86-64
    runs-on: ubuntu-latest
    steps:
    - name: Checkout sources
      uses: actions/checkout@v3
      with:
        submodules: recursive   
    - name: Install Rust
      uses: dtolnay/rust-toolchain@nightly
      with:
        toolchain: nightly-2024-01-30
        components: rustfmt
        override: true
    - name: Build
      run: cargo build --release --package mini-ola
    - name: Upload binary
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: target/release/mini-ola
        asset_name: mini-ola-linux-x86-64
        tag: ${{ github.ref }}
        overwrite: true
  mac-intel:
    name: Mac Intel
    runs-on: macos-latest
    steps:
    - name: Checkout sources
      uses: actions/checkout@v3
      with:
        submodules: recursive   
    - name: Install Rust
      uses: dtolnay/rust-toolchain@nightly
      with:
        toolchain: nightly-2024-01-30
        components: rustfmt  
        override: true
    - name: Build
      run: cargo build --release --package mini-ola
    - name: Upload binary
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: target/release/mini-ola
        asset_name: mini-ola-mac-intel
        tag: ${{ github.ref }}
        overwrite: true
  macos-arm:
    name: Mac ARM
    runs-on: macos-latest-xlarge
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: recursive  
    - name: Install Rust
      uses: dtolnay/rust-toolchain@nightly
      with:
        toolchain: nightly-2024-01-30
        components: rustfmt
        override: true
    - name: Build
      run: cargo build --release --package mini-ola
    - name: Upload binary
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: target/release/mini-ola
        asset_name: mini-ola-mac-arm
        tag: ${{ github.ref }}
        overwrite: true
  windows:
    name: Windows
    runs-on: windows-latest
    steps:
    - name: Checkout sources
      uses: actions/checkout@v3
      with:
        submodules: recursive   
    - name: Install Rust
      uses: dtolnay/rust-toolchain@nightly
      with:
        toolchain: nightly-2024-01-30
        components: rustfmt
        override: true
    - name: Build
      run: cargo build --release --package mini-ola
    - name: Upload binary
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: target/release/mini-ola.exe
        asset_name: mini-ola-windows.exe
        tag: ${{ github.ref }}
        overwrite: true
