name: CI checks

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      # - name: Cache Rust toolchain
      #   uses: actions/cache@v2
      #   with:
      #     path: |
      #       ~/.cargo/bin
      #       ~/.cargo/registry
      #       ~/.cargo/git
      #       ~/.rustup
      #     key: ${{ runner.os }}-rustup-${{ hashFiles('**/rust-toolchain') }}-${{ github.sha }}
      #     restore-keys: |
      #       ${{ runner.os }}-rustup-${{ hashFiles('**/rust-toolchain') }}-
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-2024-01-31
          profile: minimal
          components: rustfmt, clippy
          override: true
      - name: check
        run: cargo check --all-features
      - name: fmt-check
        run: cargo fmt --all -- --check
      - name: Clippy
        run: cargo clippy
      - name: Build
        run: cargo build
      # - name: Run tests
      #   run: cargo test --verbose
